spring:
  application:
    name: spring-ai-chat-bot
  ai:
    ollama:
      init:
        pull-model-strategy: when_missing
      chat:
        model: hf.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF # https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF
      embedding:
        model: bge-m3

app:
  rag:
    documents-location-pattern: classpath:research.pdf
  etl:
    pipeline:
      init: true

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG